import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getMonthName } from './dateHelpers';

export function generateBillPDF(entries, totals, providers, year, month, paymentInfo = { status: 'Pending', method: 'Cash' }) {
  const doc = new jsPDF();
  const monthName = getMonthName(month);

  // Header
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129); // emerald
  doc.text('Hisaab', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('Milk Delivery Tracking', 14, 27);

  // Bill Title
  doc.setFontSize(16);
  doc.setTextColor(50, 50, 50);
  doc.text(`Monthly Bill - ${monthName} ${year}`, 14, 40);

  // Provider Info
  if (entries.length > 0) {
    const providerId = entries[0].providerId;
    const provider = providers.find(p => p.id === providerId);
    if (provider) {
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      doc.text(`Provider: ${provider.name}`, 14, 50);
      doc.text(`Rate: Rs. ${provider.ratePerLitre}/L`, 14, 56);
      if (provider.contact) doc.text(`Contact: ${provider.contact}`, 14, 62);
    }
  }

  // Date range
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 140, 50);

  // Table
  const tableData = entries.map(entry => {
    return [
      new Date(entry.date + 'T00:00:00').toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
      }),
      entry.milk.morning.toString(),
      entry.milk.evening.toString(),
      (entry.milk.morning + entry.milk.evening).toFixed(1),
      `Rs. ${entry.milk.ratePerLitre}`,
      `Rs. ${entry.milk.totalAmount.toFixed(2)}`,
      entry.newspaper.taken ? `Rs. ${entry.newspaper.rate}` : '-',
      `Rs. ${entry.totalAmount.toFixed(2)}`,
    ];
  });

  autoTable(doc, {
    startY: 70,
    head: [['Date', 'Morning', 'Evening', 'Total (L)', 'Rate', 'Milk Amt', 'Paper', 'Total']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    columnStyles: {
      0: { cellWidth: 25 },
      7: { fontStyle: 'bold' },
    },
  });

  // Summary
  const finalY = doc.lastAutoTable.finalY + 10;

  doc.setFontSize(12);
  doc.setTextColor(50, 50, 50);
  doc.text('Bill Summary', 14, finalY);

  doc.setFontSize(10);
  const summaryStartY = finalY + 8;
  doc.text(`Total Milk: ${totals.totalMilk.toFixed(1)} L`, 14, summaryStartY);
  doc.text(`Milk Amount: Rs. ${totals.totalMilkAmount.toFixed(2)}`, 14, summaryStartY + 6);
  doc.text(`Newspaper Amount: Rs. ${totals.totalNewspaper.toFixed(2)}`, 14, summaryStartY + 12);
  doc.text(`Days Delivered: ${totals.daysDelivered}`, 110, summaryStartY);
  doc.text(`Days Missed: ${totals.daysMissed}`, 110, summaryStartY + 6);

  // Grand Total
  doc.setFontSize(14);
  doc.setTextColor(16, 185, 129);
  doc.text(`Grand Total: Rs. ${totals.totalAmount.toFixed(2)}`, 14, summaryStartY + 24);

  // Monthly Payment Status
  doc.setFontSize(11);
  const paymentY = summaryStartY + 36;
  if (paymentInfo.status === 'Paid') {
    doc.setTextColor(16, 185, 129); // emerald green
    doc.text(`Payment Status: Paid (via ${paymentInfo.method})`, 14, paymentY);
  } else {
    doc.setTextColor(220, 38, 38); // red
    doc.text('Payment Status: Pending', 14, paymentY);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Hisaab - Milk Delivery Tracking App', 14, 285);

  // Save
  doc.save(`Hisaab_Bill_${monthName}_${year}.pdf`);
}
